load("@rules_java//java:defs.bzl", "java_import")

java_import(
    name = "junit_jars",
    jars = [
      "hamcrest-core-1.3.jar",
      "junit-4.13.jar"
    ],
    visibility = ["//test:__subpackages__"]
)