on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
name: ContinuousIntegration
jobs:
  checks:
    name: Build Libraries and Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Mount Bazel Cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install Bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Build Utils
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //src/utils:utils
    - name: Build Problem Solutions
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //src/problems:problem_solutions
    - name: Run Unit Tests
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test //test:all

    - name: build_utils
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: build //src/utils:utils
    - name: build_problems
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: build //src/problems:problem_solutions
    - name: run_tests
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: test //test:all
