on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
name: ContinuousIntegration
jobs:
  checks:
    name: Build Libraries and Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Install Bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Build Utils
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //src/utils:utils

    - name: Build Problem Solutions
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //src/problems:problem_solutions

    - name: Run Unit Tests
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test --test_output=errors //test:all
    - name: Format Code
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COMMIT_MSG: |
          Automated: Format Code
          skip-checks: true	
      run: |
        git config user.email ""
        git config user.name "Automated Code Formatter"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/nkprasad12/euler.git
        java -jar "${GITHUB_WORKSPACE}/lib/google-java-format-1.7-all-deps.jar" -i $(git ls-files)
        chmod +x "${GITHUB_WORKSPACE}/lib/buildifier"
        "${GITHUB_WORKSPACE}/lib/buildifier" -r "${GITHUB_WORKSPACE}"
        git diff --quiet && git diff --staged --quiet || (git commit -a -m "${COMMIT_MSG}"; git push origin ${{ github.head_ref }})
