on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
name: BuildTest
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build_utils
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: build //src/utils:utils
    - name: build_problems
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: build //src/problems:problem_solutions