on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
name: ContinuousIntegration
jobs:
  checks:
    name: build_and_run_tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build_utils
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: build //src/utils:utils
    - name: build_problems
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: build //src/problems:problem_solutions
    - name: run_tests
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: test //test:all
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: testlogs
        path: /github/home/.cache/bazel/_bazel_root/3ef6b2ad9cc100f006a5d4a7217ff063/execroot/__main__/bazel-out/k8-fastbuild/testlogs